package ca.ulaval.glo4002.game.domain.action;

public enum GameActionType {
    ADD_CHARACTER,
    ADD_MOVIE,
    ALL_LOSE_HAMSTAGRAM_FOLLOWERS,
    ALL_LOSE_REPUTATION_POINTS,
    ALL_HIRE_LAWYER,
    ALL_SETTLE_LAWSUITS,
    ALL_LOSE_MONEY,
    ALL_CHECK_AND_ELIMINATE,
    RESET_GAME,
    ALL_PAY_AGENT,
    RATTEDIN_CONTACT_REQUEST,
    ALL_MOVIES_CHANGE_STEP,
    ALL_AGENTS_REPRESENTATION_REQUEST,
    ALL_CHARACTERS_NEXT_TURN,
    CHARACTER_TO_CHARACTER_ACTION,
    ALL_PAY_LAWYER
}
